Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> #Spotify Listening History Analysis
... 
... Welcome to the **Spotify Listening History Analysis** project!  
... This project helps you analyze your personal Spotify data using Python and some powerful data science libraries like **NumPy**, **Pandas**, **Matplotlib**, and **Seaborn**.
... 
... ---
... 
... # Objectives
... 
... This project explores your Spotify listening behavior based on your history data. The key objectives include:
... 
... - **Top Tracks and Artists**  
...   Identify the songs and artists you listen to the most.
... 
... -  **Time-Based Patterns**  
...   Analyze what time of day you listen to music most often.
... 
... -  **Platform Usage**  
...   Understand which platforms (desktop, mobile, etc.) you use the most.
... 
... -  **Skip Behavior**  
...   Discover how often you skip songs and when.
... 
... - **Shuffle Impact**  
...   Compare listening behavior when shuffle mode is on vs off.
... 
... ---
... 
... ## ️ Project Structure
... 
